# Generated by Django 4.1.5 on 2023-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': u"Состояние доставки",
                'verbose_name_plural': u"Состояния доставок",
            },
        ),
    ]
